#!/bin/bash

#exit an any error
set -e

function get_config_var()
{
	cat config.json | grep "\"$1\"" | sed -e 's/.*": //' -e 's/,$//' -e 's/^"//' -e 's/"$//'
}


PORT=$(get_config_var serial_port)
BAUD=$(get_config_var serial_baudrate)
COM_DEV=$(get_config_var serial_device)
if [[ "$COM_DEV" == "2" || "$COM_DEV" == "3" ]]; then
	echo "Skip connecting. UART device is disabled in configuration."
else
	if [ ! -f ./uart_to_abmt ] || [ uart_to_abmt.cpp -nt ./uart_to_abmt ]; then
		echo "Compile uart_to_abmt..."
		g++ -std=c++17 -g uart_to_abmt.cpp -I./shared ./shared/src/linux/io/eio.cpp ./shared/src/linux/util/bt_exception.cpp -o uart_to_abmt
	fi
	./uart_to_abmt $PORT $BAUD
fi
